spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/project_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 20
      driver-class-name: org.postgresql.Driver
      auto-commit: true
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/project_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    #    locations: classpath:/db
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: public
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  jpa:
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
---

jwtconfig:
  secret: secret
  expiration: 60000